---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-from-istio-gateway
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: demo-web
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: istio-ingress
          podSelector:
            matchLabels:
              gateway.networking.k8s.io/gateway-name: lab-gateway
      ports:
        - protocol: TCP
          port: 8080
